#! /usr/bin/env python
import sys
import cubi.engine as engine
import cubi.logger as logger
import cubi.params as params
from cubi.engine import Servant;

from pygments.formatters import HtmlFormatter
from pygments.lexers import get_lexer_by_name
from pygments import highlight

class PygmentServant(Servant):

    def _init(self, engine, adapter):
        fmter = HtmlFormatter(nowrap=True)
        fmter.encoding = 'ascii'
        self.fmter = fmter
        self._lexer_list = {}
        pass

    def _get_lexer(self, lang):
        if lang not in self._lexer_list:
            lexer = get_lexer_by_name(lang)
            lexer.encoding = 'ascii'
            self._lexer_list[lang] = lexer
        return self._lexer_list[lang]

    @params.extract_args
    def highlight(self, lang, code):

        # if self.debug and logger.is_debug():
        #     logger.get_logger().debug("highlight: %s %s", lang, code)

        lexer = self._get_lexer(lang)
        html = highlight(code, lexer, self.fmter)

        result = {}
        result['data'] = html;
        return result

if __name__ == '__main__':

    # logger.enable_debug_log()

    endp = "pygments@tcp::2016"
    setting = {}
    setting['debug'] = True
    setting['endpoint'] = endp
    engine.make_easy_engine('pygments', PygmentServant, setting).serve_forever()
